---
title: "WordRec Experiment"
author: "A. Fourtassi & M. Frank"
date: "January 13, 2017"
output:
  html_document:
    number_sections: yes
    toc: yes
---

Libraries.

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(langcog)
theme_set(theme_bw())
```

The following analysis is done using pilot data with 25 subjects.

We plan to collect data for 100 subjects

Data. 

```{r}

#Skip the pre task trials 
#Filter subjects who had no technical problem
#Select subjects who got more than 50% correct answers on the pre task trials

d <- read_delim("data_pilot.txt", delim = " ") %>%
  filter(type == "Task", problem=="No", score>0.5)
```

Break out by conditions. 
```{r}
sounds <- d %>%
  filter(condition == "sound") %>%
  group_by(sound_dist) %>%
  multi_boot_standard(col = "answer")

concepts <- d %>%
  filter(condition == "concept") %>%
  group_by(concept_dist) %>%
  multi_boot_standard(col = "answer")

joint <- d %>%
  filter(condition == "joint") %>%
  group_by(concept_dist, sound_dist) %>%
  multi_boot_standard(col = "answer")

ggplot(joint, 
       aes(x = sound_dist, y = mean, col = factor(concept_dist))) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_line(lty = 2) + 
  geom_line(data = sounds, aes(col = 1), col = "black") + 
  geom_pointrange(data = sounds, aes(ymin = ci_lower, ymax = ci_upper, 
                                     col = 1), col = "black")+
  xlab("Auditory distance") +ylab("% different")+
  scale_colour_discrete(name="Visual Dist")+
theme(legend.title = element_text(size=8))

ggplot(joint, 
       aes(x = concept_dist, y = mean, col = factor(sound_dist))) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_line(lty = 2) + 
  geom_line(data = concepts, aes(col = 1), col = "black") + 
  geom_pointrange(data = concepts, aes(ymin = ci_lower, ymax = ci_upper, 
                                     col = 1), col = "black") + 
  scale_colour_solarized() +
  xlab("Visual distance") +ylab("% different")+
  scale_colour_discrete(name="Auditory Dist")+
theme(legend.title = element_text(size=8))

```

Fit the models.
```{r}

#Fit the uniomodal sound condition
sound_data <- d %>%
    filter(condition == "sound")

concept_data <- d %>%
    filter(condition == "concept")

joint_data <- d %>%
    filter(condition == "joint")

#Fit the uniomodal sound condition with a logistic regression
fit_sound <- glm(answer ~ sound_dist, data=sound_data, family = binomial())

##extract coefficient
s_coef <- coef(fit_sound)["sound_dist"]
s_inter <- coef(fit_sound)["(Intercept)"]

#prameters of the sound distribution
s_var=4/(s_coef)
s_sum=-1*s_inter/s_coef

#Fit the uniomodal visual conditon
fit_concept <- glm(answer ~ concept_dist, data=concept_data, family = binomial())

##extract coefficient
c_coef <- coef(fit_concept)["concept_dist"]
c_inter <- coef(fit_concept)["(Intercept)"]

#prameters of the sound distribution
v_var=4/(c_coef)
v_sum=-1*c_inter/c_coef

#Fit the bimodal conditon
fit_joint <- glm(answer ~ sound_dist+concept_dist, data=joint_data, family = binomial())

##extract coefficient
j_coef_a <- coef(fit_joint)["sound_dist"]
j_coef_v <- coef(fit_joint)["concept_dist"]
j_inter <- coef(fit_joint)["(Intercept)"]

#prameters of the sound distribution (approx: the average mean sum equal to 0+4/2=2)
j_var_a=4/(j_coef_a)
j_var_v=4/(j_coef_v)

```


Analysis of the unimodal cases.
```{r}

#Recogniton functions from the unimodal fit 
x <- seq(0, 4, 0.01)

y_sound <- predict(fit_sound, list(sound_dist = x), type="response")
y_concept <- predict(fit_concept, list(concept_dist = x), type="response")

uniS <- data.frame(xS=x,yS=y_sound)
uniV <- data.frame(xV=x,yV=y_concept)

#Recognition functions from the bimodal fit (marginal distributions)
Logistic_a = function (x, A = j_coef_a , B = 2*j_coef_a) {
    1 / (1 + exp(-1*(-B +A * x)))
}

Logistic_v = function (x, A = j_coef_v , B = 2*j_coef_v) {
    1 / (1 + exp(-1*(-B +A * x)))
}

#Plot all these functions in the same graph

##The auditory case
ggplot(sounds, 
       aes(x = sound_dist, y = mean)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_line(data=uniS,aes(x=xS, y=yS))+
  xlab("Auditory distance") +ylab("% different")+
  scale_y_continuous(limits = c(0, 1))+
  stat_function(fun = Logistic_a, colour="red")

##The visual case
ggplot(concepts, 
       aes(x = concept_dist, y = mean)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_line(data=uniV,aes(x=xV, y=yV))+
  xlab("Visual distance") +ylab("% different")+
  scale_y_continuous(limits = c(0, 1))+
  stat_function(fun = Logistic_v, colour="red")
 

```

The bimodal case
```{r}

# Bimodal recognition functions

##the bimodal fit 
model_fit <- function (x,y) {
   1/(1 + exp(-x*j_coef_a-y*j_coef_v+2*j_coef_a+2*j_coef_v))
}

##Values of the baseline
model_base <- function (x,y) {
   1/(1 + exp(-x*s_coef-y*c_coef+2*s_coef+2*c_coef))
}

# Add the fit the baeline to data

ms_all <- joint %>% 
  rename(joint = mean) %>%
  left_join(select(concepts, concept_dist, mean) %>% 
              rename(concepts = mean)) %>%
  left_join(select(sounds, sound_dist, mean) %>% 
              rename(sounds = mean)) %>%
  mutate(fit = model_fit(sound_dist, concept_dist)) %>%
  mutate(base = model_base(sound_dist, concept_dist)) %>%
  gather(model, pred, concepts, sounds, base, fit)

#Plot Heat map for the data
ggplot(data = ms_all, aes(x=sound_dist, y=concept_dist, fill=joint)) + 
  geom_tile()+scale_fill_continuous(limits=c(0, 1))+xlab("Auditory distance") +ylab("Visual distance")


#Plot Heatmap for the baseline
mybase <- ms_all %>%
  filter(model=="base")

ggplot(data = mybase, aes(x=sound_dist, y=concept_dist, fill=pred)) + 
  geom_tile()+scale_fill_continuous(limits=c(0, 1))+xlab("Auditory distance") +ylab("Visual distance")

myfilter <- ms_all %>%
  filter(model=="fit" | model=="base")

#Correlation models (baseline and fit) to bimodal data 
ggplot(myfilter, 
       aes(x = pred, y = joint, col = factor(concept_dist), 
           shape = factor(sound_dist))) +
 geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_abline(slope = 1, lty = 2) +
  facet_grid(model~.)



```

The modality dominance
```{r}

#Modality dominance coeficent
a_fit=j_var_v/j_var_a
a_base=v_var/s_var
a_Vdom=2*a_base
a_Sdom=0.5*a_base

#Classification thresholds (prob=0.5) for:

##The basline (combination of the unimodal cases)
classif_base = function (x, A=a_base) {
    2*(A+1)-A*x
}

##Best bivariate fit 
classif_fit = function (x, A=a_fit) {
    2*(A+1)-A*x
}

##A baseline for visual domiance
classif_Vdom = function (x, A=a_Vdom) {
    2*(A+1)-A*x
}

##A baseline for auditory domiance
classif_Sdom = function (x, A=a_Sdom) {
    2*(A+1)-A*x
}

#Sample from the baseline bivariate distribution
Gaus_base <- data.frame(x=c(rnorm(1000,0,sqrt(s_var)),rnorm(1000,4,sqrt(s_var))),
          y=c(rnorm(1000,0,sqrt(v_var)),rnorm(1000,4,sqrt(v_var))))

#Plot samples from the bivariate distribution
ggplot(Gaus_base, aes(x,y)) +  stat_density2d(geom="contour",aes(alpha=..level..))+
  scale_alpha_continuous(limits=c(0,0.03),breaks=1e-6*seq(0,10,by=2))+
  stat_function(fun = classif_base, colour = "red") +xlab("Auditory") +ylab("Visual")+ scale_x_continuous(limits = c(-6, 10))+scale_y_continuous(limits = c(-6, 10))

#Sample from the best bivariate fit 
Gaus_fit <- data.frame(x=c(rnorm(1000,0,sqrt(j_var_a)),rnorm(1000,4,sqrt(j_var_a))),
          y=c(rnorm(1000,0,sqrt(j_var_v)),rnorm(1000,4,sqrt(j_var_v))))

#Plot samples from the best bivariate fit
ggplot(Gaus_fit, aes(x,y)) +  stat_density2d(geom="contour",aes(alpha=..level..))+
  scale_alpha_continuous(limits=c(0,0.03),breaks=1e-6*seq(0,10,by=2))+
  stat_function(fun = classif_fit, colour = "red") +xlab("Auditory") +ylab("Visual") + scale_x_continuous(limits = c(-6, 10))+scale_y_continuous(limits = c(-6, 10))

#Modality dominance?
ggplot(Gaus_fit, aes(x,y)) +
  stat_function(fun = classif_base, colour = "red", lty=2) +
  stat_function(fun = classif_Vdom, colour = "blue", lty=2 )+
  stat_function(fun = classif_Sdom, colour = "blue", lty=2)+
  stat_function(fun = classif_fit, colour = "black")+
  xlab("Auditory") +ylab("Visual") + scale_x_continuous(limits = c(-6, 10))+
  scale_y_continuous(limits = c(-6, 10))+theme(aspect.ratio = 1)

```








