---
title: "WordRec Experiment"
author: "A. Fourtassi"
date: "November 26, 2018"
output:
  html_document:
    number_sections: yes
    toc: yes
---
Libraries.

```{r}
#library(papaja)
library(broom)
  library(purrr)
  library(readr)
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  #library(wordbankr)
  library(stringr)
  library(feather)
  library(lme4)
  library(boot)
  library(langcog)
  library(ggthemes)
  library(nlme)
  #library(rwebppl)
  library(jsonlite)
  library(Hmisc)
  library(poweRlaw)
  library(HDInterval)
  #library(kableExtra)
```

Data and processing
```{r}

#Skip the pre task trials 
#Filter subjects who had no technical problem
#Select subjects who got more than 50% correct answers on the pre task trials

exp1 <- read_delim("exp1_rev2_anonym.txt", delim = " ") %>%
  filter(type == "Task") %>%
  mutate(experiment='Experiment1')

N_all_1 <- exp1 %>%
  distinct(ID) %>%
  nrow()
  
exp1_noProb <- exp1 %>%
  filter(problem=="No") 

N_noProb_1 <- exp1_noProb %>%
  distinct(ID) %>%
  nrow()

exp1_good <- exp1_noProb %>%
  filter(score >= 0.75)

N_good_1 <- exp1_good %>%
  distinct(ID) %>%
  nrow()

sound_all_exp1 <- exp1_good %>%
    filter(condition == "sound")

concept_all_exp1 <- exp1_good %>%
    filter(condition == "concept")

joint_all_exp1 <- exp1_good %>%
    filter(condition == "joint")


```

Fit the aggregate  data 
```{r}
data_s <- sound_all_exp1 %>%
  group_by(sound_dist) %>%
  dplyr::summarise(mean = mean(answer),
                   sd = sd(answer),
                   n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
  select(-sd, -n, -se,) %>%
  mutate(Experiment="Experiment 1", 
         Condition="Auditory") %>%
  rename(distance = sound_dist)

data_c <- concept_all_exp1 %>%
  group_by(concept_dist) %>%
  dplyr::summarise(mean = mean(answer),
                   sd = sd(answer),
                   n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
  select(-sd, -n, -se,) %>%
  mutate(Experiment="Experiment 1", 
         Condition="Visual") %>%
  rename(distance = concept_dist)

data_j <- joint_all_exp1 %>%
  group_by(sound_dist, concept_dist) %>%
  dplyr::summarise(mean = mean(answer),
                   sd = sd(answer),
                   n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
  select(-sd, -n, -se,) %>%
  mutate(Experiment="Experiment 1", 
         Condition="Joint") 

data_all <- bind_rows(data_s, data_c)

model_s <- nls(answer ~ 1/(1+(1-e)*exp((-4/vrA)*sound_dist+(8/vrA))), data=sound_all_exp1, start = list(e=0, vrA=2))
model_c <- nls(answer ~ 1/(1+(1-e)*exp((-4/vrV)*concept_dist+(8/vrV))), data=concept_all_exp1, start = list(e=0, vrV=2))
model_j <- nls(answer ~ 1/(1+(1-e)*exp((-4/vrA_j)*sound_dist+(-4/vrV_j)*concept_dist+(8/vrA_j)+(8/vrV_j))), data=joint_all_exp1, start = list(e=0, vrA_j=2, vrV_j=2))

#Plot the data here
x <- seq(0, 4, 0.01)

y_s <- predict(model_s, list(sound_dist = x), type="response")
y_c <- predict(model_c, list(concept_dist = x), type="response")

pred_all <- bind_rows(data.frame(distance=x, prediction=y_s, Condition = "Auditory"), 
                      data.frame(distance=x, prediction=y_c, Condition = "Visual")) 
  
#Derive values of the variance from the 
ggplot(data_all, 
       aes(x = distance, y = mean)) + 
  geom_point()+
  geom_pointrange(aes(ymin = lower, ymax = upper), 
                  position = position_dodge(width = .1), size = 0.4, fatten = 2) + 
  #geom_line(data=uniV,aes(x=xV, y=yV))+
  geom_line(data=pred_all, aes(x=distance, y=prediction), col='black')+
  #geom_line(data=uni_me_s, aes(x=distance, y=prediction), col='blue')+
  #geom_line(data=uni_nl_s, aes(x=distance, y=prediction), col='red')+
  xlab("Distance") +ylab("Prob. different")+
  scale_y_continuous(limits = c(0, 1))+#theme(aspect.ratio = 0.7)+
  theme_few()+
  theme(aspect.ratio = 0.7) + facet_grid(. ~ Condition)


```
Optimal model
```{r}
#Extract cefficieny

eA <- coefficients(model_s)["e"]
vrA <- coefficients(model_s)["vrA"]

eV <- coefficients(model_c)["e"]
vrV <- coefficients(model_c)["vrV"]

ej <- coefficients(model_j)["e"]
vrAj <- coefficients(model_j)["vrA_j"]
vrVj <- coefficients(model_j)["vrV_j"]

#The sound-only model
m_s <- function (x,y) {
  1/(1 + (1-eA)*exp((-4/vrA)*x+(8/vrA)))
}

#The visual-only model
m_c <- function (x,y) {
  1/(1 + (1-eV)*exp((-4/vrV)*y+(8/vrV)))
}

#Descriptive model (parameters are derived from fit to bimodal data)
m_opt <- function (x,y) {
   1/(1 + (1-ej)*exp((-4/vrA)*x+(-4/vrV)*y+(8/vrA)+(8/vrV)))
}

#The optimal model (parameters are derived from fit to unimodal data)
m_des <- function (x,y) {
    1/(1 + (1-ej)*exp((-4/vrAj)*x+(-4/vrVj)*y+(8/vrAj)+(8/vrVj)))
}

pred_all_comb <- data_j %>% 
  rename(joint = mean) %>%
  mutate(Descriptive = m_des(sound_dist, concept_dist)) %>%
  mutate(Optimal = m_opt(sound_dist, concept_dist)) %>%
  mutate(Auditory = m_s(sound_dist, concept_dist)) %>%
  mutate(Visual = m_c(sound_dist, concept_dist)) %>%
  gather(model, pred, Visual, Auditory, Optimal, Descriptive) %>%
  mutate(experiment = 'Experiment 1')


pred_all_comb$model <- factor(pred_all_comb$model, levels = c('Visual','Auditory', 'Optimal', 'Descriptive'))

correlations <- pred_all_comb %>%
  group_by(model) %>%
  summarise(cor = round(cor(joint, pred), 2))

ggplot(pred_all_comb, 
       aes(x = pred, y = joint)) +
           #col = factor(concept_dist), 
          # shape = factor(sound_dist))) + 
  geom_point(size =1)+
  scale_colour_solarized()+
 #geom_pointrange(aes(ymin = summary_ci_lower, ymax = summary_ci_upper), 
  #                position = position_dodge(width = .1), size=0.2) + 
  geom_abline(slope = 1, lty = 2) +
  xlab("Predictions") +ylab("Human data")+
  facet_grid(. ~ model)+
  theme_few()+
  geom_text(data=correlations, aes(label=paste("r=", cor, sep="")), x=0.5, y=0.95, size=2, fontface = "bold", col="red")+
theme(aspect.ratio = 0.7, 
      axis.text=element_text(size=6),
      strip.text.y = element_text(size = 8))+
  guides(color=guide_legend(title="Visual Distance")) +
  guides(shape=guide_legend(title="Auditory Distance")) 






```



Human data by subject
```{r}

sounds_exp1 <- exp1_good %>%
  filter(condition == "sound") %>%
  group_by(ID, sound_dist) %>%
  dplyr::summarise(mean = mean(answer),
                   sd = sd(answer),
                   n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
  select(-sd, -n, -se,) %>%
  mutate(Experiment="Experiment 1", 
         Condition="Auditory") %>%
  rename(distance = sound_dist)

concepts_exp1 <- exp1_good %>%
  filter(condition == "concept") %>%
  group_by(ID, concept_dist) %>%
  dplyr::summarise(mean = mean(answer),
                   sd = sd(answer),
                   n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
  select(-sd, -n, -se,) %>%
  mutate(Experiment="Experiment 1", 
         Condition="Visual") %>%
  rename(distance = concept_dist)


joint_exp1 <- exp1_good %>%
  filter(condition == "joint") %>%
  group_by(ID, concept_dist, sound_dist) %>%
  summarise(mean = mean(answer)) %>%
  mutate(Experiment="Experiment 1", 
         Condition="Joint")


exp_uni_data <- bind_rows(sounds_exp1, concepts_exp1)
```

Here fit the same models for every subject
```{r}

#Models 

#Sound Unimodal
fit_s <- function(data) {
  nls(answer ~ 1/(1+(1-e)*exp((-4/vrA)*sound_dist+(8/vrA))), 
                 data=data,
                 start = list(e=0, vrA=1),
                 nls.control(warnOnly = TRUE)) 
}
#Concept Unimodal
fit_c <- function(data) {
  nls(answer ~ 1/(1+(1-e)*exp((-4/vrV)*concept_dist+(8/vrV))), 
                 data=data,
                 start = list(e=0, vrV=1),
                 nls.control(warnOnly = TRUE)) 
}

#Joint sound-concept
fit_j <- function(data) {
  nls(answer ~1/(1+(1-e)*exp((-4/vrA_j)*sound_dist+(-4/vrV_j)*concept_dist+(8/vrA_j)+(8/vrV_j))), 
                 data=data,
                 start = list(e=0, vrA_j=1, vrV_j=1),
                 nls.control(warnOnly = TRUE)) 
}

##Fit the models for each subject

#Split data by subject 
data_by_subj_s <- split(sound_all_exp1, sound_all_exp1$ID) 
data_by_subj_c <- split(concept_all_exp1, concept_all_exp1$ID)
data_by_subj_j <- split(joint_all_exp1, joint_all_exp1$ID)

#.. and fit
model_by_subj_s <- map(data_by_subj_s, fit_s) 
model_by_subj_c <- map(data_by_subj_c, fit_c)
model_by_subj_j <- map(data_by_subj_j, fit_j)

```

Unimodal conditions
```{r}
## Generate model predictions to plot with human data in the unimodal conditions

x <- seq(0, 4, 0.01)

pred_s <- function(model, ID){
  y <- predict(model, list(sound_dist = x), type="response")
  data.frame(distance=x, prediction=y, ID=ID) 
}

pred_c <- function(model, ID){
  y <- predict(model, list(concept_dist = x), type="response")
  data.frame(distance=x, prediction=y, ID=ID) 
}

ID <- as.list(strsplit(names(model_by_subj_s), " "))

#Generate  predictions for each subject
pred_s <- map2(model_by_subj_s, ID, model_pred_s) %>%
  bind_rows()
pred_c <- map2(model_by_subj_c, ID, model_pred_c) %>%
  bind_rows()

##Plot

ggplot(sounds_exp1, 
       aes(x = distance, y = mean)) + 
  geom_point()+
  #geom_pointrange(aes(ymin = lower, ymax = upper), 
  #                position = position_dodge(width = .1), size = 0.4, fatten = 2) + 
  #geom_line(data=uniV,aes(x=xV, y=yV))+
  geom_line(data=pred_s, aes(x=distance, y=prediction), col='black')+
  #geom_line(data=uni_me_s, aes(x=distance, y=prediction), col='blue')+
  geom_line(data=pred_nl_s, aes(x=distance, y=prediction), col='red')+
  xlab("Distance") +ylab("Prob. different")+
  scale_y_continuous(limits = c(0, 1))+#theme(aspect.ratio = 0.7)+
  theme_few()+
  theme(aspect.ratio = 0.7) + facet_grid(. ~ ID)

ggplot(concepts_exp1, 
       aes(x = distance, y = mean)) + 
  geom_point()+
  #geom_pointrange(aes(ymin = lower, ymax = upper), 
  #                position = position_dodge(width = .1), size = 0.4, fatten = 2) + 
  #geom_line(data=uniV,aes(x=xV, y=yV))+
  geom_line(data=pred_c, aes(x=distance, y=prediction), col='black')+
  #geom_line(data=uni_me_s, aes(x=distance, y=prediction), col='blue')+
  geom_line(data=pred_nl_c, aes(x=distance, y=prediction), col='red')+
  xlab("Distance") +ylab("Prob. different")+
  scale_y_continuous(limits = c(0, 1))+#theme(aspect.ratio = 0.7)+
  theme_few()+
  theme(aspect.ratio = 0.7) + facet_grid(. ~ ID)

  
  

```

Here compute the optimal combination
```{r}

##Extract coefficients from unimodal condition to build the optimal model and compare to descriptive model

#Unimodal coefficients
 co_uni <- function(model, ID) {
   data.frame(bias=coefficients(model)[1], 
              variance=coefficients(model)[2], 
              ID=ID)
 }
 
 #Bimodal coefficients
 co_bim <- function(model, ID) {
   data.frame(bias=coefficients(model)[1],
              var_s=coefficients(model)[2],
              var_c=coefficients(model)[3],
              ID=ID)
 }

#Here extract ceofficients to build optimal model later
coef_s <- map2(model_by_subj_s, ID, co_uni) %>%
  bind_rows() %>%
  rename(vrA_u= variance,
         bA_u =  bias)

coef_c <- map2(model_by_subj_c, ID, co_uni) %>%
  bind_rows() %>%
  rename(vrV_u= variance,
         bV_u =  bias)

coef_j <- map2(model_by_subj_j, ID, co_bim) %>%
  bind_rows() %>%
  rename(vrA_j = var_s,
         vrV_j = var_c,  
         b =  bias)


## Below are functions that take sound and concept distances and return the predicted joint value in each model

# Sound only
model_s <- function (data, x,y) {
  vrA = unique(data$vrA_u)
  b = unique(data$bA_u)
  
  1/(1 + (1-b)*exp((-4/vrA)*x+(8/vrA)))
}

# Visual only
model_c <- function (data, x,y) {
  vrV = unique(data$vrV_u)
  b = unique(data$bV_u)
  
  1/(1 + (1-b)*exp((-4/vrV)*y+(8/vrV)))
}

# Optimal
model_opt <- function (data, x,y) {
  vrA = unique(data$vrA_u)
  vrV = unique(data$vrV_u)
  e   = unique(data$b)
  
  1/(1 + (1-e)*exp((-4/vrA)*x+(-4/vrV)*y+(8/vrA)+(8/vrV)))
}

# Descriptive
model_des <- function (data, x,y) {
  vrA = unique(data$vrA_j)
  vrV = unique(data$vrV_j)
  e   = unique(data$b)
  
  1/(1 + (1-e)*exp((-4/vrA)*x+(-4/vrV)*y+(8/vrA)+(8/vrV)))
}


data_models <- joint_exp1 %>%
  left_join(coef_s) %>%
  left_join(coef_c) %>%
  left_join(coef_j)
  

models <- function (subject_data) {
  subject_data %>% rename(Joint = mean) %>%
  mutate(Descriptive = model_des(subject_data, sound_dist, concept_dist)) %>%
  mutate(Optimal = model_opt(subject_data, sound_dist, concept_dist)) %>%
  mutate(Auditory = model_s(subject_data, sound_dist, concept_dist)) %>%
  mutate(Visual = model_c(subject_data, sound_dist, concept_dist)) %>%
  gather(model, pred, Visual, Auditory, Optimal, Descriptive) 
}

data_by_subj <- split(data_models, data_models$ID) 

data_preds <- map(data_by_subj, models) %>%
  bind_rows()

data_preds$model <- factor(data_preds$model, levels = c('Visual','Auditory', 'Optimal', 'Descriptive'))

correlations <- data_preds %>%
  group_by(ID, model) %>%
  summarise(cor = round(cor(Joint, pred), 2))

ggplot(data_preds, 
       aes(x = pred, y = Joint)) +
           #col = factor(concept_dist), 
          # shape = factor(sound_dist))) + 
  geom_point(size =1)+
  scale_colour_solarized()+
 #geom_pointrange(aes(ymin = summary_ci_lower, ymax = summary_ci_upper), 
  #                position = position_dodge(width = .1), size=0.2) + 
  geom_abline(slope = 1, lty = 2) +
  xlab("Predictions") +ylab("Human data")+
  facet_grid(ID ~ model)+
  theme_few()+
  geom_text(data=correlations, aes(label=paste("r=", cor, sep="")), x=0.5, y=0.95, size=2, fontface = "bold", col="red")+
theme(aspect.ratio = 0.7, 
      axis.text=element_text(size=6),
      strip.text.y = element_text(size = 8))+
  guides(color=guide_legend(title="Visual Distance")) +
  guides(shape=guide_legend(title="Auditory Distance")) 




```
